version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y zip

  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo Build phase...
      - echo "<html><body><h1>Hello World</h1></body></html>" > index.html
      - mkdir -p output
      - cp -r index.html appspec.yml scripts/ output/
      - cd output
      - zip -r deployment.zip *

  post_build:
    commands:
      - echo Post-build phase...
      - aws s3 cp deployment.zip s3://cicd-project-artifacts/
artifacts:
  files:
    - output/deployment.zip
  discard-paths: yes

